---
- name: "lookup apiKey from secret into namespace"
  vars:
    secret_name: "{{ ansible_operator_meta.name }}-monetdb-secret"
  set_fact:
    secret_apikey_content: "{{ lookup('k8s', kind='Secret', namespace=ansible_operator_meta.namespace, resource_name=secret_name ) }}"

- name: "generate password random"
  set_fact:
    monet_admin_password:  "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=10') }}"
  when: (secret_apikey_content|length==0)

- name: "obtain  password from existing"
  set_fact:
    monet_admin_password:  "{{ secret_apikey_content.data.MDB_DB_ADMIN_PASS | b64decode  }}"
  when: (secret_apikey_content|length>0)

- name: create secret
  kubernetes.core.k8s:
    definition:
        kind: Secret
        apiVersion: v1
        metadata:
            name: '{{ ansible_operator_meta.name }}-monetdb-secret'
            namespace: '{{ ansible_operator_meta.namespace }}'
            labels:
              app: '{{ app_name }}'
              release: '{{ ansible_operator_meta.name }}'
              generated: "true"
              app.kubernetes.io/instance: '{{ ansible_operator_meta.name }}'
              app.kubernetes.io/managed-by: '{{ meta.labels.managenby }}'
              app.kubernetes.io/name: '{{ meta.labels.name }}'
        stringData:
          MDB_DAEMON_PASS: '{{ monet_admin_password }}'
          MDB_DB_ADMIN_PASS: '{{ monet_admin_password }}'