        apiVersion: v1
        kind: Service
        metadata:
          name: 'monetdb-service'
        spec:
          type: ClusterIP
          ports:
            - name: 50000-tcp
              protocol: TCP
              port: 50000
              targetPort: 50000
          selector:
            component: 'monetdb'