apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator-for-monetdb.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: It deploy a MonetDb instance on your cluster
  displayName: Operator for MonetDb
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monet
  - monetdb
  links:
  - name: Operator For Monetdb
    url: https://operator-for-monetdb.domain
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.0
