---
- name: create service account
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: monetdb-service-account
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
            app: '{{ app_name }}'
            release: '{{ ansible_operator_meta.name }}'
            generated: "true"
            app.kubernetes.io/instance: '{{ ansible_operator_meta.name }}'
            app.kubernetes.io/managed-by: '{{ meta.labels.managenby }}'
            app.kubernetes.io/name: '{{ meta.labels.name }}'
